services:
  ollama1:
    image: ollama/ollama
    container_name: ollama1
    ports:
      - "11436:11434"
    volumes:
      - C:/code/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: always

  ollama2:
    image: ollama/ollama
    container_name: ollama2
    ports:
      - "11435:11434"
    volumes:
      - C:/code/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: always

  ollama-loadbalancer:
    build: ./loadbalancer
    container_name: ollama-loadbalancer
    ports:
      - "11434:11434"


networks:
  default:
    name: hekthon
    external: true
