services:
  selenium-hub:
    image: selenium/hub:4.22.0-20240621
    container_name: selenium-hub
    ports:
      - "4442-4444:4442-4444"
    restart: always

  selenium-chrome:
    deploy:
      mode: replicated
      replicas: 9
    image: selenium/node-chrome:4.22.0-20240621
    restart: always
    shm_size: 2g
    mem_limit: 2g
    environment:
      SE_NODE_MAX_SESSIONS: 1
      SE_START_XVFB: false
      # SE_NODE_OVERRIDE_MAX_SESSIONS: true
      # SE_ENABLE_BROWSER_LEFTOVERS_CLEANUP: true
      SE_NODE_SESSION_TIMEOUT: 14
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_DRAIN_AFTER_SESSION_COUNT: 10
      SE_SCREEN_WIDTH: 1366 
      SE_SCREEN_HEIGHT: 768 
      SE_SCREEN_DEPTH: 24
      SE_SCREEN_DPI: 74

  mongo-cache:
    image: mongo
    restart: always
    container_name: mongo-cache
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-cache:/data/db
    ports:
      - "27017:27017"


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo-cache:27017/
      ME_CONFIG_BASICAUTH: false

  python-ui:
    container_name: python-ui
    build: .
    restart: always
    ports:
      - 8888:8888
    command:  /bin/bash -c 'while true; do python ui.py || sleep 3; done'
    environment:
      HD_HOST: 0.0.0.0
      TEMPORAL_ADDRESS: "temporal:7233"
      MONGO_HOSTNAME: "mongo-cache"
      SELENIUM_ADDRESS: "http://selenium-hub:4444"
    volumes:
      - .:/app:ro

volumes:
  mongo-cache:



networks:
  default:
    name: hekthon
    external: true