services:
  selenium-hub:
    image: selenium/hub:4.22.0-20240621
    container_name: selenium-hub
    ports:
      - "4442-4444:4442-4444"
    restart: always

  selenium-chrome:
    deploy:
      mode: replicated
      replicas: 9
    image: selenium/node-chrome:4.22.0-20240621
    restart: always
    shm_size: 2g
    mem_limit: 2g
    environment:
      SE_NODE_MAX_SESSIONS: 1
      SE_START_XVFB: false
      # SE_NODE_OVERRIDE_MAX_SESSIONS: true
      # SE_ENABLE_BROWSER_LEFTOVERS_CLEANUP: true
      SE_NODE_SESSION_TIMEOUT: 14
      SE_EVENT_BUS_HOST: ${SELENIUM_IP:-selenium-hub}
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_DRAIN_AFTER_SESSION_COUNT: 10
      SE_SCREEN_WIDTH: 1366 
      SE_SCREEN_HEIGHT: 768 
      SE_SCREEN_DEPTH: 24
      SE_SCREEN_DPI: 74


  # mongo-atlas:
  #   image: mongodb/mongodb-atlas-local:latest
  #   restart: always
  #   container_name: mongo-atlas
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   volumes:
  #     - mongo-atlas:/data/db
  #   ports:
  #     - "27018:27017"

  
  mongo-cache:
    image: mongo
    restart: always
    container_name: mongo-cache
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-cache:/data/db
    ports:
      - "27017:27017"


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo-cache:27017/
      ME_CONFIG_BASICAUTH: false


  
  neo4j:
    image: neo4j:5.21.0
    container_name: neo4j
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_AUTH=neo4j/your_password
    volumes:
      - neo4j_data:/data
      - neo4j_plugins:/plugins

  neo4j-browser:
    build: docker-neo4j-browser
    container_name: neo4j-browser
    restart: always
    ports:
      - "8082:8080"
    environment:
      - "NEO4j=http://neo4j:7687"

  python-ui:
    container_name: python-ui
    build: .
    restart: always
    ports:
      - 8888:8888
    command:  /bin/bash -c 'while true; do python ui.py || sleep 3; done'
    environment:
      - HD_HOST=0.0.0.0
      - TEMPORAL_ADDRESS=${TEMPORAL_ADDRESS:-temporal:7233}  
      - MONGO_HOSTNAME=${MONGO_HOSTNAME:-mongo-cache}  
      - SELENIUM_IP=${SELENIUM_IP:-selenium-hub}
      - IFRAME_IP
      - LLAMAINDEX_HOST 
      - NEO4J_HOSTNAME=${NEO4J_HOSTNAME:-neo4j}
    volumes:
      - .:/app:ro

  
  python-browser-worker:
    container_name: python-browser-worker
    build: .
    restart: always
    command:  /bin/bash -c 'while true; do python browser-worker.py || sleep 3; done'
    environment:
      - HD_HOST=0.0.0.0
      - TEMPORAL_ADDRESS=${TEMPORAL_ADDRESS:-temporal:7233}  
      - MONGO_HOSTNAME=${MONGO_HOSTNAME:-mongo-cache}  
      - SELENIUM_IP=${SELENIUM_IP:-selenium-hub}
      - IFRAME_IP
      - LLAMAINDEX_HOST
      - NEO4J_HOSTNAME=${NEO4J_HOSTNAME:-neo4j}
    volumes:
      - .:/app:ro


volumes:
  mongo-cache:    
  mongo-atlas:    
  neo4j_data:
  neo4j_plugins:


networks:
  default:
    name: hekthon
    external: true