file:
  # use_llama_parse: Use LlamaParse if `true`. Needs a `LLAMA_CLOUD_API_KEY` from https://cloud.llamaindex.ai set as environment variable
  use_llama_parse: true
db:
  # The configuration for the database loader, only supports MySQL and PostgreSQL databases for now.
  # uri: The URI for the database. E.g.: mysql+pymysql://user:password@localhost:3306/db or postgresql+psycopg2://user:password@localhost:5432/db
  # query: The query to fetch data from the database. E.g.: SELECT * FROM table
  - uri: mysql+pymysql://user:pass@localhost:3306/mydb
    queries:
      - SELECT * FROM mytable
